name: CI

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }} ${{ matrix.node }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: |
          deno fmt --check
          deno lint
